Usuarios/urls.py
from django.urls import path, include, reverse_lazy
import Usuarios.views
from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views



urlpatterns = [
    path('login/', Usuarios.views.login_user, name='login_user'),
    path('consola_estudiantes/', Usuarios.views.consola_estudiantes, name='consola_estudiantes'),
    path('realizar-pago-semestre/', views.realizar_pago_semestre, name='realizar_pago_semestre'),
    path('actualizar_perfil/', views.actualizar_perfil, name='actualizar_perfil'),
    
    path('consola_financiera/', Usuarios.views.consola_financiera, name='consola_financiera'),
    path('perfil_estudiante/', Usuarios.views.perfil_estudiante, name="perfil_estudiante"),
    path('financiera/perfil_financiera/', Usuarios.views.perfil_financiera, name="perfil_financiera"),
    path('actualizar_perfil_financiera/', views.actualizar_perfil_financiera, name='actualizar_perfil_financiera'),
    path('transacciones_financiera/', views.transacciones_financiera, name='transacciones_financiera'),
    
    path('mainApp/', include('mainApp.urls', namespace='main_app')),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('main_app:inicio')), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WalletUCC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('usuario/', include('Usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

app_name = 'mainApp'


urlpatterns = [
    path('', views.index, name='inicio'),
]

Usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError




class Usuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    identificacion = models.PositiveIntegerField(unique=True)
    email = models.EmailField()
    foto_perfil = models.ImageField(upload_to='Usuarios/img/Perfil', default='Usuarios/img/Perfil/default.png', blank=True)
    amigos = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"


class Estudiante(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    valor_semestre_estudiante = models.DecimalField(max_digits=15, decimal_places=2)
    creditos_registrados_estudiante = models.PositiveIntegerField()
    semestre_a_pagar_estudiante = models.PositiveIntegerField()
    
    aumento_1 = models.BooleanField(default=False)
    aumento_2 = models.BooleanField(default=False)
    aumento_3 = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.usuario.nombres} {self.usuario.apellidos} - Semestre {self.semestre_a_pagar_estudiante}"

    class Meta:
        verbose_name = "Estudiante"
        verbose_name_plural = "Estudiantes"


class Cuenta(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE, related_name='cuenta')
    saldo_usuario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.usuario.user.username

    class Meta:
        verbose_name = "Cuenta"
        verbose_name_plural = "Cuentas"


ESTADO_PENDIENTE = 'pendiente'
ESTADO_PAGADA = 'pagada'
ESTADO_ABONADO = 'abonado'

ESTADO_CHOICES = [
    (ESTADO_PENDIENTE, 'Pendiente'),
    (ESTADO_PAGADA, 'Pagada'),
    (ESTADO_ABONADO, 'Abonado'),
]

class Financiera(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    saldo_financiera = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ultima_actualizacion_financiera = models.DateTimeField(auto_now=True)

    # Fechas limites de pago
    fecha_limite_pago_1 = models.DateField()
    fecha_limite_pago_2 = models.DateField()
    fecha_limite_pago_3 = models.DateField()

    
    
    def __str__(self):
        return f"Financiera {self.usuario.username}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Financiera"
        verbose_name_plural = "Financieras"


class Transaccion(models.Model):
    origen = models.CharField(max_length=255)
    
    financiera = models.ForeignKey(
        Financiera,
        on_delete=models.CASCADE,
        related_name='transacciones_creadas',
        null=True,
        blank=True
    )
    destino = models.ForeignKey(
        Estudiante,
        on_delete=models.CASCADE,
        related_name='transacciones_recibidas'
    )
    informacion_transaccion = models.CharField(max_length=100)
    descripcion = models.TextField()
    valor_transaccion = models.DecimalField(max_digits=10, decimal_places=2)
    monto_transaccion = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    fecha_transaccion = models.DateField(auto_now_add=True)
    hora_transaccion = models.TimeField(auto_now_add=True)
    fecha_vencimiento_transaccion = models.DateField(null=True, blank=True)
    pagada_transaccion = models.BooleanField(default=False)
    estado_transaccion = models.CharField(max_length=10, choices=ESTADO_CHOICES, default=ESTADO_PENDIENTE)

    def __str__(self):
        return f'Transacción {self.id} de Financiera a {self.destino}'

    class Meta:
        verbose_name = 'Transacción'
        verbose_name_plural = 'Transacciones'
        ordering = ['-fecha_transaccion']

class Envio(models.Model):
    id_envio = models.PositiveIntegerField(unique=True)
    origen_cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE, related_name='envios_realizados')
    destino_cuenta = models.ForeignKey(Cuenta, on_delete=models.CASCADE, related_name='envios_recibidos')
    fecha_envio = models.DateTimeField(auto_now_add=True)
    monto_envio = models.DecimalField(max_digits=10, decimal_places=2)
    estado_envio = models.BooleanField(default=False)

    def __str__(self):
        return f'Envío {self.id_envio} de {self.origen_cuenta.usuario.nombres} {self.origen_cuenta.usuario.apellidos} a {self.destino_cuenta.usuario.nombres} {self.destino_cuenta.usuario.apellidos}'

    class Meta:
        verbose_name = "Envío"
        verbose_name_plural = "Envíos"

    def clean(self):
        if self.origen_cuenta.saldo_usuario < self.monto_envio:
            raise ValidationError('El usuario no tiene suficiente saldo para realizar este envío')

    def save(self, *args, **kwargs):
        if not self.pk:
            # Verificar que el usuario tenga suficiente saldo para realizar el envío
            if self.origen_cuenta.saldo_usuario < self.monto_envio:
                raise ValidationError('El usuario no tiene suficiente saldo para realizar este envío')
            # Restar el monto de la cuenta del origen
            self.origen_cuenta.saldo_usuario -= self.monto_envio
            self.origen_cuenta.save()
            # Añadir el monto a la cuenta del destino
            self.destino_cuenta.saldo_usuario += self.monto_envio
            self.destino_cuenta.save()
        super().save(*args, **kwargs)

Usuarios/views.py
import decimal
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib import messages
from Usuarios.models import Financiera
from datetime import date, datetime
from django.contrib import messages
from django.shortcuts import render, redirect
from Usuarios.models import Usuario, Estudiante, Financiera, Transaccion
from dateutil import parser




from decimal import Decimal
from django.http import HttpResponse

import locale

# Configuración para localizar el formato de números en español (Colombia)
locale.setlocale(locale.LC_ALL, 'es_CO.UTF-8')

class ObservadorSemestre:
    def __init__(self, estudiante, financiera):
        self.estudiante = estudiante
        self.financiera = financiera

    def actualizar(self, request):
        fecha_actual = date.today()
        fecha_limite_pago_1 = self.financiera.fecha_limite_pago_1
        fecha_limite_pago_2 = self.financiera.fecha_limite_pago_2
        fecha_limite_pago_3 = self.financiera.fecha_limite_pago_3

        if fecha_actual > fecha_limite_pago_1 and not self.estudiante.aumento_1:
            self.aumentar_semestre(request, 1)
        elif fecha_actual > fecha_limite_pago_2 and not self.estudiante.aumento_2:
            self.aumentar_semestre(request, 2)
        elif fecha_actual > fecha_limite_pago_3 and not self.estudiante.aumento_3:
            self.aumentar_semestre(request, 3)

    def aumentar_semestre(self, request, aumento):
        if aumento == 1:
            incremento = Decimal('0.02')
            self.estudiante.valor_semestre_estudiante += self.estudiante.valor_semestre_estudiante * incremento
            self.estudiante.aumento_1 = True
            mensaje = "¡Se ha aplicado el primer aumento al semestre!"
        elif aumento == 2:
            incremento = Decimal('0.05')
            self.estudiante.valor_semestre_estudiante += self.estudiante.valor_semestre_estudiante * incremento
            self.estudiante.aumento_2 = True
            mensaje = "¡Se ha aplicado el segundo aumento al semestre!"
        elif aumento == 3:
            incremento = Decimal('0.10')
            self.estudiante.valor_semestre_estudiante += self.estudiante.valor_semestre_estudiante * incremento
            self.estudiante.aumento_3 = True
            mensaje = "¡Se ha aplicado el tercer aumento al semestre!"

        self.estudiante.save()
        messages.info(request, mensaje)


def login_user(request):
    if request.user.is_authenticated:
        usuario = Usuario.objects.get(user=request.user)

        if Estudiante.objects.filter(usuario=usuario).exists():
            return redirect('consola_estudiantes')

        if Financiera.objects.filter(usuario=request.user).exists():
            return redirect('consola_financiera')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            usuario = Usuario.objects.get(user=user)
            if Estudiante.objects.filter(usuario=usuario).exists():
                return redirect('consola_estudiantes')

            if Financiera.objects.filter(usuario=user).exists():
                return redirect('consola_financiera')

        error_message = 'Usuario o contraseña inválidos'
        return render(request, 'Usuarios/login.html', {'error_message': error_message})
    
    return render(request, 'Usuarios/login.html')


# Lo que se llama cada vez que se recarga la consola estudiantes
def realizar_pago_semestre(request):
    if request.method == 'POST':
        opcion = request.POST.get('opcion')
        usuario = request.user.usuario
        estudiante = usuario.estudiante
        cuenta = usuario.cuenta

        if opcion == 'pago_total':
            saldo_suficiente = cuenta.saldo_usuario >= estudiante.valor_semestre_estudiante
            if saldo_suficiente:
                cuenta.saldo_usuario -= Decimal(estudiante.valor_semestre_estudiante)
                cuenta.save()
                estudiante.valor_semestre_estudiante = Decimal(0)
                estudiante.save()
                messages.success(request, '¡Pago realizado!')
            else:
                messages.error(request, 'Saldo insuficiente para realizar el pago total del semestre.')
        elif opcion == 'abono':
            valor_abono = request.POST.get('valor_abono')
            if valor_abono:
                valor_abono = Decimal(valor_abono)
                if valor_abono <= cuenta.saldo_usuario:
                    estudiante.valor_semestre_estudiante -= valor_abono
                    cuenta.saldo_usuario -= valor_abono
                    cuenta.save()
                    estudiante.save()
                    messages.success(request, '¡Abono realizado!')
                    if estudiante.valor_semestre_estudiante == Decimal(0):
                        messages.info(request, '¡Se ha completado el pago total del semestre!')
                else:
                    messages.error(request, 'Saldo insuficiente para realizar el abono.')
            else:
                messages.error(request, 'Ingrese un valor válido para el abono.')

    return redirect('consola_estudiantes')

@login_required
def consola_estudiantes(request):
    fecha_actual = date.today()

    usuario = request.user.usuario  # se invoca al usuario que está en línea

    # Fechas límites de pago que el estudiante tiene para pagar el semestre
    financieras = Financiera.objects.all()
    primera_financiera = financieras.first()

    fechas_limites_pago = [primera_financiera.fecha_limite_pago_1, primera_financiera.fecha_limite_pago_2, primera_financiera.fecha_limite_pago_3]


    # Crear instancia del observador del semestre y actualizar
    observador_semestre = ObservadorSemestre(usuario.estudiante, primera_financiera)
    observador_semestre.actualizar(request)

    # Obtener los mensajes y pasarlos al contexto
    mensajes = []
    for mensaje in messages.get_messages(request):
        mensajes.append(mensaje)

    # Se traen los datos del usuario
    nombre_completo = f"{usuario.nombres} {usuario.apellidos}"
    saldo = usuario.cuenta.saldo_usuario
    saldo_str = f"{saldo:,}"
    semestre_pagar = usuario.estudiante.semestre_a_pagar_estudiante
    valor_semestre_str = f"{usuario.estudiante.valor_semestre_estudiante:,}"
    
    foto_perfil = f"{usuario.foto_perfil}"

    context = {
        'fecha_actual': fecha_actual,
        'nombre_completo': nombre_completo,
        'saldo': saldo,
        'saldo_str': saldo_str,
        'semestre_pagar': semestre_pagar,
        'valor_semestre_str': valor_semestre_str,
        'fechas_limites_pago': fechas_limites_pago,
        'mensajes': mensajes,
        'foto_perfil': foto_perfil
    }

    return render(request, 'Estudiantes/consola_estudiantes.html', context)


@login_required
def actualizar_perfil(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        foto_perfil = request.FILES.get('foto_perfil')

        usuario = request.user.usuario
        usuario.email = email

        if foto_perfil:
            # Validar que el archivo sea de tipo PNG
            if not foto_perfil.name.lower().endswith('.png'):
                return redirect('perfil_estudiante')

            # Guardar la foto de perfil en el campo 'foto_perfil' del modelo
            usuario.foto_perfil.save(foto_perfil.name, foto_perfil)

        usuario.save()

    return redirect('perfil_estudiante')

@login_required
def perfil_estudiante(request):
    usuario = request.user.usuario

    nombre_completo = f"{usuario.nombres} {usuario.apellidos}"
    nombre = f"{usuario.nombres}"
    apellidos = f"{usuario.apellidos}"
    
    email = f"{usuario.email}"
    foto_perfil = f"{usuario.foto_perfil}"
    
    identificacion = f"{usuario.identificacion}"

    return render(request, 'Estudiantes/perfil_estudiante.html', {
        'nombre_completo': nombre_completo,
        'nombre' : nombre,
        'apellidos': apellidos,
        'email': email,
        'foto_perfil': foto_perfil,
        'identificacion': identificacion,
    })


@login_required
def perfil_financiera(request):
    usuario = request.user.usuario

    nombre_completo = f"{usuario.nombres} {usuario.apellidos}"
    nombre = f"{usuario.nombres}"
    apellidos = f"{usuario.apellidos}"
    
    email = f"{usuario.email}"
    foto_perfil = f"{usuario.foto_perfil}"
    
    identificacion = f"{usuario.identificacion}"

    return render(request, 'Financiera/perfil_financiera.html', {
        'nombre_completo': nombre_completo,
        'nombre' : nombre,
        'apellidos': apellidos,
        'email': email,
        'foto_perfil': foto_perfil,
        'identificacion': identificacion,
    })

@login_required
def actualizar_perfil_financiera(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        foto_perfil = request.FILES.get('foto_perfil')

        usuario = request.user.usuario
        usuario.email = email

        if foto_perfil:
            # Validar que el archivo sea de tipo PNG
            if not foto_perfil.name.lower().endswith('.png'):
                return redirect('perfil_financiera')

            # Guardar la foto de perfil en el campo 'foto_perfil' del modelo
            usuario.foto_perfil.save(foto_perfil.name, foto_perfil)

        usuario.save()

    return redirect('perfil_financiera')


@login_required
def consola_financiera(request):
    usuario = request.user.usuario
    financiera = Financiera.objects.first()

    if request.method == 'POST':
        fecha_limite_pago_1 = request.POST.get('fecha_limite_pago_1')
        fecha_limite_pago_2 = request.POST.get('fecha_limite_pago_2')
        fecha_limite_pago_3 = request.POST.get('fecha_limite_pago_3')

Usuarios/templates/Financiera/consola_financiera.html
{% extends 'Usuarios/consola.html' %}
{% load static %}

{% block extra_styles %}

{% endblock %}



{% block items_nav_dashboard_lateral %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'consola_financiera' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Semestre</span>
        </a>
    </li>

            <!-- Divisor -->
            <hr class="sidebar-divider">

            <!-- Encabezamiento -->
            <div class="sidebar-heading">
                Mi cuenta
            </div>

            <!-- Elemento de navegación - Páginas Menú Contraer -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'transacciones_financiera' %}"
                    aria-expanded="true">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Transacciones</span>
                </a>
            </li>

            <!-- Elemento de navegación - Utilidades Menú Contraer -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Movimientos</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Personalizar</h6>
                        <a class="collapse-item" href="utilities-color.html">Colores</a>
                        <a class="collapse-item" href="utilities-border.html">Bordes</a>
                        <a class="collapse-item" href="utilities-animation.html">Animaciones</a>
                        <a class="collapse-item" href="utilities-other.html">Otros</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Plugins
            </div>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Usuarios</span></a>
            </li>


{% endblock %}

{% block Mi_cuenta %}"{% url 'perfil_financiera' %}"{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Consola Financiera</h1>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Saldo (Disponible)</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">${{ saldo_str }} COP</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Fechas Límites de Pago</h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="fecha_limite_pago_1">Fecha Límite de Pago 1</label>
                        <input type="date" class="form-control" id="fecha_limite_pago_1" name="fecha_limite_pago_1" value="{{ fecha_limite_pago_1|default_if_none:'' }}" required>
                    </div>
                    <div class="form-group">
                        <label for="fecha_limite_pago_2">Fecha Límite de Pago 2</label>
                        <input type="date" class="form-control" id="fecha_limite_pago_2" name="fecha_limite_pago_2" value="{{ fecha_limite_pago_2|default_if_none:'' }}" required>
                    </div>
                    <div class="form-group">
                        <label for="fecha_limite_pago_3">Fecha Límite de Pago 3</label>
                        <input type="date" class="form-control" id="fecha_limite_pago_3" name="fecha_limite_pago_3" value="{{ fecha_limite_pago_3|default_if_none:'' }}" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                </form>
            </div>
        </div>
    </div>

    {% block Extra_JsScript %}
    {% endblock %}
{% endblock %}

Usuarios/templates/Financiera/perfil_financiera.html
{% extends 'Financiera/consola_financiera.html' %}
{% load static %}

{% block extra_styles %}
<link href="{% static 'Estudiantes\css\perfil_estudiante.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" action="{% url 'actualizar_perfil_financiera' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="text-center">
                        <img id="profile-pic-preview" src="../../../media/{{ foto_perfil }}" alt="Profile Picture" class="profile-pic">
                        <div class="custom-file mt-2">
                            <input type="file" class="custom-file-input" id="profile-pic-input" name="foto_perfil" accept=".png">
                            <label class="custom-file-label" for="profile-pic-input">Seleccionar archivo</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="first-name">Nombres</label>
                        <input type="text" class="form-control" id="first-name" name="nombre" value="{{ nombre }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="last-name">Apellidos</label>
                        <input type="text" class="form-control" id="last-name" name="apellidos" value="{{ apellidos }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="email">Correo Electrónico</label>
                        <input type="email" class="form-control" id="email" name="email" value="{{ email }}">
                    </div>
                    <div class="form-group">
                        <label for="identification">Identificación</label>
                        <input type="text" class="form-control" id="identification" name="identificacion" value="{{ identificacion }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="friend-list">Lista de amigos</label>
                        <select multiple class="form-control" id="friend-list">
                            <option>Amigo 1</option>
                            <option>Amigo 2</option>
                            <option>Amigo 3</option>
                            <option>Amigo 4</option>
                            <option>Amigo 5</option>
                        </select>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% block Extra_JsScript %}
    <script src="{% static 'Estudiantes\js\perfil_estudiante.js' %}"></script>
    {% endblock %}
{% endblock %}

Usuarios/templates/Financiera/transacciones_financiera.html
{% extends 'Financiera/consola_financiera.html' %}
{% load static %}

{% block extra_styles %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.7.2/dist/css/bootstrap.min.css">
    <link href="{% static 'Financiera/css/transacciones_financiera.html' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Crear Transacción</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_origen" class="form-label">Origen:</label>
                <input type="text" id="id_origen" class="form-control" value="Financiera" readonly>
            </div>
            <div class="mb-3">
                <label for="id_destino" class="form-label">Destino:</label>
                <select name="destino" id="id_destino" class="form-select">
                    {% for nombre_apellido in nombres_apellidos_estudiantes %}
                        <option value="{{ forloop.counter }}">{{ nombre_apellido }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="id_informacion_transaccion" class="form-label">Información de la Transacción:</label>
                <select name="informacion_transaccion" id="id_informacion_transaccion" class="form-select">
                    <option value="Certificado">Certificado</option>
                    <option value="Pago de Semestre">Pago de Semestre</option>
                    <option value="Otro">Otro</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="id_descripcion" class="form-label">Descripción:</label>
                <textarea name="descripcion" id="id_descripcion" class="form-control"></textarea>
            </div>
            <div class="mb-3">
                <label for="id_valor_transaccion" class="form-label">Valor de la Transacción:</label>
                <input type="number" step="0.01" name="valor_transaccion" id="id_valor_transaccion" class="form-control">
            </div>
            <div class="mb-3">
                <label for="id_monto_transaccion" class="form-label">Monto de la Transacción:</label>
                <input type="number" step="0.01" name="monto_transaccion" id="id_monto_transaccion" class="form-control">
            </div>
            <div class="mb-3">
                <label for="id_fecha_vencimiento" class="form-label">Fecha de Vencimiento:</label>
                <input type="date" name="fecha_vencimiento" id="id_fecha_vencimiento" class="form-control">
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Crear Transacción</button>
            </div>
        </form>

        <h1 class="text-center mt-5">Transacciones Existentes</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Origen</th>
                    <th>Destino</th>
                    <th>Información de la Transacción</th>
                    <th>Descripción</th>
                    <th>Valor de la Transacción</th>
                    <th>Monto de la Transacción</th>
                    <th>Fecha de Vencimiento</th>   
                </tr>
            </thead>
            <tbody>
                {% for transaccion in transacciones %}
                    <tr>
                        <td>{{ transaccion.origen }}</td>
                        <td>{{ transaccion.destino }}</td>
                        <td>{{ transaccion.informacion_transaccion }}</td>
                        <td>{{ transaccion.descripcion }}</td>
                        <td>{{ transaccion.valor_transaccion }}</td>
                        <td>{{ transaccion.monto_transaccion }}</td>
                        <td>{{ transaccion.fecha_vencimiento_transaccion }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7">No hay transacciones existentes.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

Usuarios/templates/Financiera/usuarios_financiera.html
{% extends 'Financiera/consola_financiera.html' %}
{% load static %}

{% block extra_styles %}

{% endblock %}

{% block content %}
    <div class="container">
        <h1>Lista de Estudiantes</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre completo</th>
                    <th>Número de teléfono</th>
                    <th>Correo</th>
                    <th>Créditos registrados</th>
                    <th>Valor total a pagar del semestre</th>
                </tr>
            </thead>
            <tbody>
                <!-- Aquí se generan las filas de la tabla con datos de estudiantes -->
                <tr>
                    <td>Estudiante 1</td>
                    <td>1234567890</td>
                    <td>estudiante1@example.com</td>
                    <td>30</td>
                    <td>$300,000</td>
                </tr>
                <tr>
                    <td>Estudiante 2</td>
                    <td>9876543210</td>
                    <td>estudiante2@example.com</td>
                    <td>25</td>
                    <td>$250,000</td>
                </tr>
                <!-- Agrega más filas según sea necesario -->
            </tbody>
        </table>
    </div>
    {% block Extra_JsScript %}

    {% endblock %}
{% endblock %}