WalletUCC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('usuario/', include('Usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainApp/urls.py
from django.urls import path
from . import views

app_name = 'mainApp'


urlpatterns = [
    path('', views.index, name='inicio'),
]

mainApp/models.py
from django.db import models

# Create your models here.

mainApp/views.py
# Create your views here.
from django.shortcuts import render

def index(request):
    return render(request, 'mainApp/inicio.html')

mainApp/templates/mainApp/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

        <title>{% block title %}{% endblock %} | WalletUCC</title>

        <!-- Estilos CSS -->
        {% block styles %}
            <!-- CSS de Bootstrap 5 -->
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'mainApp/css/style.css' %}">

        {% endblock %}

        {% block extra_css %}

        {% endblock %}
    </head>
    <body>
        <!-- Cabecera -->
        {% block header %}
        <nav class="navbar navbar-expand-custom navbar-mainbg">
            <a class="navbar-brand navbar-logo" href="{% url 'mainApp:inicio' %}">
                <img src="{% static 'mainApp/img/logo.png' %}" alt="Logotipo de la barra de navegación" style="max-width: 30px">
                WalletUCC
            </a>
            <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-white"></i>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'mainApp:inicio' %}"><i class="fas fa-tachometer-alt"></i>INICIO</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-address-book"></i>BLOG</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="javascript:void(0);"><i class="far fa-clone"></i>SERVICIOS</a>
                    </li>
                </ul>
            </div>
        </nav>
        {% endblock %}

        <!-- Agrega el contenido principal -->
        {% block content %}
            <div class="container">
                <h1>Título Principal</h1>
                <p>Contenido principal</p>
            </div>
        {% endblock %}

        <!-- Agrega el pie de página -->
        {% block footer %}
            <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
                <div class="container text-center">
                <small>Copyright &copy; WalletUCC | Universidad Cooperativa de Colombia</small>
                </div>
            </footer>
        {% endblock %}

        <!-- Agrega los scripts -->
        {% block scripts %}
            <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
            <script src="{% static 'mainApp/js/main.js' %}"></script>

            <!-- JS de Bootstrap-->
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
        {% endblock %}

        {% block extra_js %}
        
        {% endblock %}

    </body>
</html>

mainApp/templates/mainApp/inicio.html
{% extends 'mainApp/index.html' %}
{% load static %}

{% block title %}Inicio{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/inicio.css' %}">
{% endblock %}
{% block content %}
    <div class="px-4 py-5 my-5 text-center">
        <img class="d-block mx-auto mb-4" src="{%static 'mainApp/img/logo2.png' %}" alt="" width="95" height="75">
        <h1 class="display-5 fw-bold text-body-emphasis">UNA MEJOR ALTERNATIVA</h1>
        <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Esto es una aplicacion en construccion por estudiantes de la Universidad Cooperativa de Colombia con el fin de lograr mejorar el sistema de pagos dentro de la universidad ofreciendo una mejor alternativa facil y eficaz con todos los procesos tanto para los estudiantes y administrativos.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a class="btn btn-primary btn-lg px-4 gap-3" href="{% url 'login_user' %}">Iniciar Sesión</a>
            <button type="button" class="btn btn-outline-secondary btn-lg px-4">Registrarme</button>
        </div>
        </div>
    </div>
{% endblock %}